server:
  port:8080
spring:
  datasource:
#   数据库的基本配置
    username: root
    password: asd123
    url: jdbc:mysql://localhost:3306/universityHospitalReimbursement?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
#   数据库的其他配置
    maxActive: 20
    maxWait: 60000
    dbcp2:
      initialSize: 5
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true

  #thymeleaf配置
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates
    mode: HTML
  #Redis配置
  redis:
    host: 182.92.204.177
    password: asd123
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 6
        min-idle: 0
    database: 1 #使用redis1号数据库存储数据
#日志配置
logging:
  file:
    name: my.log

